### PR TITLE
adding article compiling-lisp-to-javascript-from-scratch-in-350-loc.md

### PR DESCRIPTION
**Pull request by soupi**

### CODE REVIEW

**Comment by beerendlauwers** [comment]
Thanks for the PR! Could you change 

    authors: "Gil Mizrahi"

to

    authors: 
     - "Gil Mizrahi"

? Hakyll has an automatic fallback mechanism to parse fields as lists, but [it fails if content mixes the YAML list syntax and the Hakyll syntax.](https://github.com/jaspervdj/hakyll/issues/510)

**Comment by soupi** [comment]
No problem. Note that I used the website's gui to create the content of the file.

**Comment by beerendlauwers** [comment]
> Note that I used the website's gui to create the content of the file.

Okay, I'll update the template file accordingly.

Did you encounter any errors during the automatic pull request creation process? (After clicking the "Submit a pull request" button on the website's content submission interface)

**Comment by beerendlauwers** [comment]
Hooray, it's live! :)

http://haskanything.com/content/article/compiling-lisp-to-javascript-from-scratch-in-350-loc.html

**Comment by soupi** [comment]
Thanks!

I haven't run into problems, i just didn't want to grant account permissions to the app.

**Pull request merged**
